apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "minecharts.api.fullname" . }}
  namespace: {{ include "minecharts.namespace" . }}
  labels:
    {{- include "minecharts.labels" . | nindent 4 }}
    app: {{ include "minecharts.api.appLabel" . }}
spec:
  replicas: {{ .Values.api.replicaCount }}
  strategy:
    type: {{ .Values.api.strategy }}
  selector:
    matchLabels:
      app: {{ include "minecharts.api.appLabel" . }}
  template:
    metadata:
      labels:
        {{- include "minecharts.labels" . | nindent 8 }}
        app: {{ include "minecharts.api.appLabel" . }}
    spec:
      serviceAccountName: {{ default (include "minecharts.api.fullname" .) .Values.api.serviceAccount.name }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: minecharts-api
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.api.service.targetPort }}
          env:
            - name: MINECHARTS_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            {{- if .Values.api.env }}
            {{- toYaml .Values.api.env | nindent 12 }}
            {{- end }}
          volumeMounts:
            {{- if .Values.api.persistence.enabled }}
            - name: data-volume
              mountPath: {{ .Values.api.persistence.mountPath }}
            {{- end }}
            {{- if .Values.api.extraVolumeMounts }}
            {{- toYaml .Values.api.extraVolumeMounts | nindent 12 }}
            {{- end }}
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
      {{- if or .Values.api.persistence.enabled .Values.api.extraVolumes }}
      volumes:
        {{- if .Values.api.persistence.enabled }}
        - name: data-volume
          persistentVolumeClaim:
            claimName: {{ if .Values.api.persistence.existingClaim }}{{ .Values.api.persistence.existingClaim }}{{ else }}{{ .Values.api.persistence.claimName }}{{ end }}
        {{- end }}
        {{- if .Values.api.extraVolumes }}
        {{- toYaml .Values.api.extraVolumes | nindent 8 }}
        {{- end }}
      {{- end }}
