apiVersion: v1
kind: Service
metadata:
  name: {{ include "minecharts.api.serviceName" . }}
  namespace: {{ include "minecharts.namespace" . }}
  labels:
    {{- include "minecharts.labels" . | nindent 4 }}
    app: {{ include "minecharts.api.appLabel" . }}
spec:
  type: {{ .Values.api.service.type }}
  selector:
    app: {{ include "minecharts.api.appLabel" . }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.targetPort }}
      {{- if eq .Values.api.service.type "NodePort" }}
      nodePort: {{ .Values.api.service.nodePort }}
      {{- end }}
