apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "minecharts.web.fullname" . }}
  namespace: {{ include "minecharts.namespace" . }}
  labels:
    {{- include "minecharts.labels" . | nindent 4 }}
    app: {{ include "minecharts.web.appLabel" . }}
spec:
  replicas: {{ .Values.web.replicaCount }}
  strategy:
    type: {{ .Values.web.strategy }}
  selector:
    matchLabels:
      app: {{ include "minecharts.web.appLabel" . }}
  template:
    metadata:
      labels:
        {{- include "minecharts.labels" . | nindent 8 }}
        app: {{ include "minecharts.web.appLabel" . }}
    spec:
      serviceAccountName: {{ default (include "minecharts.web.fullname" .) .Values.web.serviceAccount.name }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: minecharts-web
          image: "{{ .Values.web.image.repository }}:{{ .Values.web.image.tag }}"
          imagePullPolicy: {{ .Values.web.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.web.service.targetPort }}
          {{- if or .Values.web.env .Values.web.secretEnv }}
          env:
            {{- if .Values.web.env }}
            {{- toYaml .Values.web.env | nindent 12 }}
            {{- end }}
            {{- range .Values.web.secretEnv }}
            - name: {{ .name }}
              valueFrom:
                secretKeyRef:
                  name: {{ .secretName }}
                  key: {{ .secretKey }}
            {{- end }}
          {{- end }}
          {{- if .Values.web.envFromSecrets }}
          envFrom:
            {{- range .Values.web.envFromSecrets }}
            - secretRef:
                name: {{ . }}
            {{- end }}
          {{- end }}
          {{- if .Values.web.extraVolumeMounts }}
          volumeMounts:
            {{- toYaml .Values.web.extraVolumeMounts | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.web.resources | nindent 12 }}
      {{- if .Values.web.extraVolumes }}
      volumes:
        {{- toYaml .Values.web.extraVolumes | nindent 8 }}
      {{- end }}
