apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minecharts-prod
resources:
  - namespace.yaml
  - ../../bases
patchesStrategicMerge:
  - ingress-patch.yaml
  - env.yaml
images:
  - name: registry.prod.nasdak.fr/l.angonnet/minecharts/api
    newTag: latest
  - name: registry.prod.nasdak.fr/l.angonnet/minecharts/web
    newTag: latest
