[project]
name = "minecharts-api"
version = "1.0.0"
description = "Minechars API documentation with Material for MkDocs"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mike>=2.1.3",
    "mkdocs-macros-plugin>=1.4.0",
    "mkdocs-material>=9.6.11",
]
